spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
#    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create-drop
#              create-target: mysql_dev